services:
  fastapi_service:
    build:
      context: ./
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    container_name: taskhive-fastapi-service
    depends_on:
      - redis-cache
    networks:
      - app_network

  celery_worker:
    build:
      context: ./
      dockerfile: celery_worker/Dockerfile
    container_name: taskhive-celery-worker
    depends_on:
      - redis-cache
    networks:
      - app_network

  redis-cache:
    image: "redis:alpine"
    networks:
      - app_network
    container_name: taskhive-redis-cache
    restart: on-failure
    ports:
      - '6379:6379'

networks:
  app_network:
    driver: bridge
